/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "intro",
    "gems",
    {
      type: "category",
      label: "Gems-basics",
      items: ["Gems-basics/congratulations", "Gems-basics/create-a-blog-post"],
    },
    {
      type: "category",
      label: "Gems-Tutorial",
      items: ["tutorial-extras/translate-your-site"],
    },
  ],
};

module.exports = sidebars;
